dist: xenial
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements-test.txt
  - pip install -q coveralls
script:
  - pytest --pep8
  - pip install bandit
  - bandit -r puppetboard
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: "3.7"
