language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements-test.txt
  - pip install -q coveralls --use-wheel
script:
  - pytest --pep8
  - pip install bandit
  - bandit -r puppetboard
after_success:
  - coveralls
