name: publish 🐳 Docker image

on:
  push:
    tags:
      - "v*"

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # we want just the version as a tag, so remove the 'refs/tags/v' prefix
      - run: |
          version="${github_ref/refs\/tags\/v/}"
          echo "version=$version" >> $GITHUB_ENV
        env:
         github_ref: ${{ github.ref }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/voxpupuli/puppetboard:${{ env.version }}
